# Generated by Django 4.2.2 on 2023-07-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name",)},
        ),
    ]
